### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by RicterZ** [zTrix/zio#12]
Could you add python3 support?

<de>膜拜蓝莲花菊苣> < </del>

**Comment by zTrix** [comment]
求 Ricter 大神提 PR，python3 的 str 搞不定

**Comment by zTrix** [comment]
因为许多场景都是直接把 zio.py 直接拷贝到目标某内网服务器就直接使用，没有安装 future 等库的条件（权限，网络等因素等），所以我不知道这种情况下如何让他在不依赖任何库的单文件状态下继续可以运行，目测单独写一个可能更简单一点？

**Comment by RicterZ** [comment]
原来场景是这样吗，我一直都当作做 ppc 的时候发包用的（捂脸
具体什么问题我要和用 Python3 的小伙伴看看代码。

**Comment by zTrix** [comment]
嗯，主要有两个难点

1. 如何不依赖任何库
1. str 的处理，str 在 python3 默认就是 unicode 了，但是 python2 的意思却是 byte array。而 zio 主要处理对象是 bytearray，隐隐觉得有点疼。

**Comment by RicterZ** [comment]
cc @Xiami2012

**Comment by zTrix** [comment]
求大神们给个方案，我考虑一下怎么改

**Comment by RicterZ** [comment]
虾米在看，倒是不着急..\_(:3」∠)_

**Comment by zTrix** [comment]
我昨天已经提交了一个中间版本 fe441860 ，修了除了 str 以外的一部份兼容性问题

**Comment by Xiami2012** [comment]
折腾了一个下午~
似乎最大的工作量就是把几乎所有的 str 全部替换成 bytes 。

#### bytes 和 str 使用差异
bytes 和 str 除了 bytes 左边多个 b 前缀几乎没有操作上的差异（就我目前的使用量来看><
bytes 的相关函数必须使用同为 bytes 作为参数。
<code>b''.join([b'\x01', b'\x02'])</code>
<code>b'abc' + b'def'</code>
<code>b'abcdefgabc'.replace(b'abc', b'aaa')</code>
<code>b'example'.find(b'am')</code>
<code>re.search(rb'\w{1,16}\\.com', b'example.com')</code>
<code>b''.join([b'\x01', b'\x02',b'\x03', b'\xff'])</code>
诺~只要不写出 b'abc' + 'def' 这样的代码，基本仿照 str 的操作就行。

#### 迭代的元素差异
注意对 bytes 进行迭代的时候，每轮迭代出的是 **int** 而不是 bytes ，这点和 str 不同。
<code>b'1234'[0] = 49</code>
<code>'1234'[0] = '1'</code>

因此构造 str 的时候使用 <code>''.join([chr(i) for i in range(256)])</code> ，
而构造 bytes 得用 <code>bytes([i for i in range(256)])</code> 。
然后因为这个，py2 和 py3 的代码可能不得不用 if 分开来处理……

#### 关于从 str 转换成 bytes
总的纲领 **str -(encode)-> bytes -(decode)-> str**
对于从 os.uname 之类的库函数获得的**可打印**字符，使用 str.encode() 变成 bytes 就行。
但对于不可打印字符，不能直接 encode 。因为 [0x80, 0xFF] 这段区间的字节会被编码成 UTF-8 总之就不是原来的数据了。
为了简化逻辑，同时对用户来说，最好的方法是调用 zio 的时候直接给 bytes 类型的参数
<code>io.write(b'A' * 24 + b'\x00\x00\x00\x00')</code>
然后 zio 内部直接用就是。

#### 关于打印
如果打印 raw data ，直接 print 就行。
如果需要解析什么的（比如 '\n' 打印成真换行符），需要 decode 成 str 后再 print 。

#### 关于 tty
这个完全没深究过不知道是怎么处理数据的求指点><

#### 杂言
python3 的 socket 通信 send 用的和 recv 得到的数据全都是 bytes ，不知道 IPC 是什么，感觉应该也是 bytes 。

说到这 zio.writeline 里额外添加的 os.linesep 本地调试的时候很方便但远程的时候本地和远程不是一个系统就坑了……这个留给用户自己封装或许更好？

其实今天就主要折腾了 test/test.py 然后根据测试结果尝试改了下 zio.py ~~这样~

这周有比较急的事下周再来折腾看看~

以上。

**Comment by zTrix** [comment]
好赞！大神出手就是厉害！

关于下面这个

> 为了简化逻辑，同时对用户来说，最好的方法是调用 zio 的时候直接给 bytes 类型的参数
> io.write(b'A' * 24 + b'\x00\x00\x00\x00')

如果用户还是用了 str 的话，是不是可以直接用 ord 然后再转 byte？如果 >= 256 就 encode utf8?

```
>>> a = '\xf3'
>>> a
'ó'
>>> a.encode()
b'\xc3\xb3'
>>> a
'ó'
>>> ord(a)
243
```

**Comment by zTrix** [comment]
另外有木有 Pull Request? 

求 ><

**Comment by Xiami2012** [comment]
> 如果用户还是用了 str 的话，是不是可以直接用 ord 然后再转 byte？如果 >= 256 就 encode utf8?

可以！（我都忘了 ord 取的是字不是字节了><

> 另外有木有 Pull Request? 

这个额……虽然我是参照我今天下午的 patch 写 issue 的，但是写的时候发现了有更好的 patch 方法……

今天只改了 test/test.py ，主要就是给 print 加括号，给测试串加 b 前缀，test_tty_raw_out 这里由于 py2/py3 的构造不可打印字符串方法不同多插了好几行代码进去。我之前没想到菊苣说的那个 str2bytes 的方法……用了比较笨的处理方法，写 issue 的时候觉得那个方法问题太多，干脆让用户传 bytes ，就删了。。现在代码缺个 function 都不能运行~所以就没 commit ><

最后膜拜蓝莲花菊苣> <

**Comment by zTrix** [comment]
那就坐等 PR 咯。

（蓝莲花菊苣多但是也有我这种弱渣存在。。。

**Comment by summershrimp** [comment]
Python 2 has no longer installed by default since Ubuntu 18.04. Please consider Python 3 support.

**Comment by zTrix** [comment]
@summershrimp Thanks for your suggestion. Just considering a complete rewrite, python3 support is the .first priority.
